{
 "title": "Cluster Overview",
 "tags": [ "Cassandra" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(cassandra_completed_tasks_counter,cluster)"
    }
   },
   {
    "name": "datacenter",
    "label": "DataCenter",
    "query": {
     "query": "label_values(cassandra_completed_tasks_counter{cluster=\"$cluster\"},dc)"
    }
   },
   {
    "name": "rack",
    "label": "Rack",
    "query": {
     "query": "label_values(cassandra_completed_tasks_counter{cluster=\"$cluster\", dc=~\"$datacenter\"},rack)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(cassandra_completed_tasks_counter{cluster=\"$cluster\", dc=~\"$datacenter\", rack=~\"$rack\"},node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Coordinator requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Throughputs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(cassandra_coordinator_read_latency_rate{cluster=\"$cluster\", dc=~\"$datacenter\", rack=~\"$rack\", node=~\"$node\"})",
     "legendFormat": "read"
    },
    {
     "expr": "sum(cassandra_coordinator_scan_latency_rate{cluster=\"$cluster\", dc=~\"$datacenter\", rack=~\"$rack\", node=~\"$node\"})",
     "legendFormat": "scan"
    },
    {
     "expr": "sum(cassandra_coordinator_write_latency_rate{cluster=\"$cluster\", dc=~\"$datacenter\", rack=~\"$rack\", node=~\"$node\"})",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Request ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cassandra_coordinator_read_latency_rate{cluster=\"$cluster\", dc=~\"$datacenter\", rack=~\"$rack\", node=~\"$node\"}) / (sum(cassandra_coordinator_read_latency_rate{cluster=\"$cluster\", dc=~\"$datacenter\", rack=~\"$rack\", node=~\"$node\"}) + sum(cassandra_coordinator_scan_latency_rate{cluster=\"$cluster\", dc=~\"$datacenter\", rack=~\"$rack\", node=~\"$node\"}) + sum(cassandra_coordinator_write_latency_rate{cluster=\"$cluster\", dc=~\"$datacenter\", rack=~\"$rack\", node=~\"$node\"}))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(cassandra_coordinator_scan_latency_rate{cluster=\"$cluster\", dc=~\"$datacenter\", rack=~\"$rack\", node=~\"$node\"}) / (sum(cassandra_coordinator_read_latency_rate{cluster=\"$cluster\", dc=~\"$datacenter\", rack=~\"$rack\", node=~\"$node\"}) + sum(cassandra_coordinator_scan_latency_rate{cluster=\"$cluster\", dc=~\"$datacenter\", rack=~\"$rack\", node=~\"$node\"}) + sum(cassandra_coordinator_write_latency_rate{cluster=\"$cluster\", dc=~\"$datacenter\", rack=~\"$rack\", node=~\"$node\"}))",
     "legendFormat": "scan"
    },
    {
     "expr": "sum(cassandra_coordinator_write_latency_rate{cluster=\"$cluster\", dc=~\"$datacenter\", rack=~\"$rack\", node=~\"$node\"}) / (sum(cassandra_coordinator_read_latency_rate{cluster=\"$cluster\", dc=~\"$datacenter\", rack=~\"$rack\", node=~\"$node\"}) + sum(cassandra_coordinator_scan_latency_rate{cluster=\"$cluster\", dc=~\"$datacenter\", rack=~\"$rack\", node=~\"$node\"}) + sum(cassandra_coordinator_write_latency_rate{cluster=\"$cluster\", dc=~\"$datacenter\", rack=~\"$rack\", node=~\"$node\"}))",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by() (cassandra_coordinator_read_latency_max{cluster=\"$cluster\", dc=~\"$datacenter\", rack=~\"$rack\", node=~\"$node\"})",
     "legendFormat": "max"
    },
    {
     "expr": "max by() (cassandra_coordinator_read_latency_bucket{cluster=\"$cluster\", dc=~\"$datacenter\", rack=~\"$rack\", node=~\"$node\", quantile=\"0.5\"})",
     "legendFormat": "p50th"
    },
    {
     "expr": "max by() (cassandra_coordinator_read_latency_bucket{cluster=\"$cluster\", dc=~\"$datacenter\", rack=~\"$rack\", node=~\"$node\", quantile=\"0.99\"})",
     "legendFormat": "p99th"
    }
   ]
  },
  {
   "title": "Scan Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by() (cassandra_coordinator_scan_latency_max{cluster=\"$cluster\", dc=~\"$datacenter\", rack=~\"$rack\", node=~\"$node\"})",
     "legendFormat": "max"
    },
    {
     "expr": "max by() (cassandra_coordinator_read_latency_bucket{cluster=\"$cluster\", dc=~\"$datacenter\", rack=~\"$rack\", node=~\"$node\", quantile=\"0.5\"})",
     "legendFormat": "p50th"
    },
    {
     "expr": "max by() (cassandra_coordinator_read_latency_bucket{cluster=\"$cluster\", dc=~\"$datacenter\", rack=~\"$rack\", node=~\"$node\", quantile=\"0.99\"})",
     "legendFormat": "p99th"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by() (cassandra_coordinator_write_latency_max{cluster=\"$cluster\", dc=~\"$datacenter\", rack=~\"$rack\", node=~\"$node\"})",
     "legendFormat": "max"
    },
    {
     "expr": "max by() (cassandra_coordinator_read_latency_bucket{cluster=\"$cluster\", dc=~\"$datacenter\", rack=~\"$rack\", node=~\"$node\", quantile=\"0.5\"})",
     "legendFormat": "p50th"
    },
    {
     "expr": "max by() (cassandra_coordinator_read_latency_bucket{cluster=\"$cluster\", dc=~\"$datacenter\", rack=~\"$rack\", node=~\"$node\", quantile=\"0.99\"})",
     "legendFormat": "p99th"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Disk usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cassandra_disk_usage{cluster=\"$cluster\", dc=~\"$datacenter\", rack=~\"$rack\", node=~\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "sum by(node) (cassandra_disk_usage{cluster=\"$cluster\", dc=~\"$datacenter\", rack=~\"$rack\", node=~\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}