{
 "title": "Node details",
 "tags": [ "Cassandra" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(cassandra_disk_usage,cluster)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(cassandra_disk_usage{cluster=\"$cluster\"},node)"
    }
   },
   {
    "name": "quantile",
    "label": "Quantile",
    "query": {
     "query": "label_values(cassandra_batch_metrics_bucket,quantile)"
    }
   },
   {
    "name": "threadpool",
    "label": "Threadpools",
    "query": {
     "query": "label_values(cassandra_thread_pools,threadpool)"
    }
   },
   {
    "name": "system_caches",
    "query": {
     "query": "label_values(cassandra_system_cache_counter,cache)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Disk usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disk usage of tables",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "cassandra_disk_usage{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "{{keyspace}}.{{table}}"
    }
   ]
  },
  { "title": "Batch statements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Max latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "cassandra_batch_metrics{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "{{statement}}"
    }
   ]
  },
  {
   "title": "Percentile latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "cassandra_batch_metrics_bucket{cluster=\"$cluster\", node=\"$node\", quantile=\"$quantile\"}",
     "legendFormat": "{{statement}} @{{quantile}}"
    }
   ]
  },
  {
   "title": "System caches - $system_caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "repeat": "system_caches",
   "collapsed": true,
   "panels": [
    {
     "title": "$system_caches cache",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "cassandra_system_cache_counter{node=\"$node\", cache=\"$system_caches\", metric=\"entry_count\"}",
       "legendFormat": "{{metric}}"
      }
     ]
    },
    {
     "title": "$system_caches cache",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(cassandra_system_cache_counter{node=\"$node\", cache=\"$system_caches\", metric=\"request_count\"}[1h])",
       "legendFormat": "requests per hour"
      },
      {
       "expr": "rate(cassandra_system_cache_counter{node=\"$node\", cache=\"$system_caches\", metric=\"hit_count\"}[1h])",
       "legendFormat": "hits per hour"
      }
     ]
    }
   ]
  },
  {
   "title": "Threadpool - $threadpool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "repeat": "threadpool",
   "collapsed": true,
   "panels": [
    {
     "title": "Pending tasks - $threadpool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "cassandra_thread_pools{cluster=\"$cluster\", node=\"$node\", threadpool=\"$threadpool\"}",
       "legendFormat": "{{metric}}"
      }
     ]
    },
    {
     "title": "$threadpool task completion rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "rate(cassandra_completed_tasks_counter{cluster=\"$cluster\", node=\"$node\", threadpool=~\"$threadpool\"}[$__rate_interval])",
       "legendFormat": "tasks completed per $__rate_Interval"
      }
     ]
    }
   ]
  }
 ]
}