{
 "title": "Schema details",
 "tags": [ "Cassandra" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "dc",
    "label": "DC",
    "query": {
     "query": "label_values({cluster=\"$cluster\"},dc)"
    }
   },
   {
    "name": "rack",
    "label": "Rack",
    "query": {
     "query": "label_values({cluster=\"$cluster\"},rack)"
    }
   },
   {
    "name": "keyspace_name",
    "label": "Keyspace",
    "query": {
     "query": "label_values({cluster=\"$cluster\"},keyspace)"
    }
   },
   {
    "name": "table_name",
    "label": "Table",
    "query": {
     "query": "label_values({keyspace=\"$keyspace_name\"},table)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Disk usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cassandra_disk_usage{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=\"$keyspace_name\", table=\"$table_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max partition size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cassandra_max_partition_size{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=\"$keyspace_name\", table=\"$table_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max tombstones per read",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cassandra_tombstones_per_read{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=\"$keyspace_name\", table=\"$table_name\", metric=\"max\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "cassandra_disk_usage{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=\"$keyspace_name\", table=\"$table_name\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Max partition size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "cassandra_max_partition_size{cluster=\"$cluster\", keyspace=\"$keyspace_name\", table=\"$table_name\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "cassandra_local_read_latency_rate{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=\"$keyspace_name\", table=\"$table_name\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Scan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "cassandra_local_scan_latency_rate{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=\"$keyspace_name\", table=\"$table_name\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "cassandra_local_write_latency_rate{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=\"$keyspace_name\", table=\"$table_name\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Max read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(cassandra_local_read_latency_max{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=\"$keyspace_name\", table=\"$table_name\"})",
     "legendFormat": "max"
    },
    {
     "expr": "max(cassandra_local_read_latency_bucket{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=\"$keyspace_name\", table=\"$table_name\", quantile=\"0.5\"})",
     "legendFormat": "{{node}} p50th"
    },
    {
     "expr": "max(cassandra_local_read_latency_bucket{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=\"$keyspace_name\", table=\"$table_name\", quantile=\"0.99\"})",
     "legendFormat": "{{node}} p99th"
    }
   ]
  },
  {
   "title": "Max scan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(cassandra_local_scan_latency_max{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=\"$keyspace_name\", table=\"$table_name\"})",
     "legendFormat": "max"
    },
    {
     "expr": "max(cassandra_local_scan_latency_bucket{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=\"$keyspace_name\", table=\"$table_name\", quantile=\"0.5\"})",
     "legendFormat": "{{node}} p50th"
    },
    {
     "expr": "max(cassandra_local_scan_latency_bucket{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=\"$keyspace_name\", table=\"$table_name\", quantile=\"0.99\"})",
     "legendFormat": "{{node}} p99th"
    }
   ]
  },
  {
   "title": "Max write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(cassandra_local_write_latency_max{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=\"$keyspace_name\", table=\"$table_name\"})",
     "legendFormat": "max"
    },
    {
     "expr": "max(cassandra_local_write_latency_bucket{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=\"$keyspace_name\", table=\"$table_name\", quantile=\"0.5\"})",
     "legendFormat": "{{node}} p50th"
    },
    {
     "expr": "max(cassandra_local_write_latency_bucket{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=\"$keyspace_name\", table=\"$table_name\", quantile=\"0.99\"})",
     "legendFormat": "{{node}} p99th"
    }
   ]
  }
 ]
}