---
services:
  victoria:
    image: victoriametrics/victoria-metrics:v1.63.0
    container_name: victoria
    command:
      - -storageDataPath=/victoria-metrics-data
      - -promscrape.config=/scraper-config.yaml
    ports:
      - 8428:8428
    volumes:
      - "${VICTORIA_DATA_DIR:-victoria}:/victoria-metrics-data"
      - "./victoria/scraper_config.yaml:/scraper-config.yaml"
      - "./cassandra_targets.json:/cassandra_targets.json"
  grafana:
    image: grafana/grafana:11.5.1
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    volumes:
      - "${GRAFANA_DATA_DIR:-grafana}:/var/lib/grafana"
      - "./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml"
      - "./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml"
      - "../dashboards:/var/lib/grafana/dashboards/Apache Cassandra Dashboards:ro"
volumes:
  victoria:
  grafana:
